### ISSUE TITLE
Not specifying baudrate will hang lpcflash on Linux

### ISSUE THREAD

**Issue by rgsilva** [devio/lpcflash#1]
Hi,

I'm running lpcflash on a Linux machine and it hangs if I don't specify the baudrate.

```
ricardo@pios ~/Projekt/lpcflash $ sudo ./lpcflash -f ~/Projekt/ddk-arm/ddk-arm.bin -l /dev/ttyUSB0 -v
^C

ricardo@pios ~/Projekt/lpcflash $ sudo ./lpcflash -f ~/Projekt/ddk-arm/ddk-arm.bin -b 115200 -l /dev/ttyUSB0
[*] 
[*] Detected part ID = 0x26013733:
[*]    Total number of 4k/32k ROM sectors: 0x15
[*]    Part serial no: 0x0400101B AFD28864 503E555D F5001E44
[*]         Boot code: 0x2
[*] 
[+] erasing sectors 0 - 21 - done.
D2: mem->img_sector_last = 14
D2: mem->img_total_size = a0000
[*] Firmware image /home/ricardo/Projekt/ddk-arm/ddk-arm.bin:
[*]       Size (bytes): 0xA0000

(...)
```

Note that the help specify that the default baudrate is 115200, so I wouldn't have to specify it manually to make it work.

Regards,

Ricardo

**Comment by nedos** [comment]
Okay looks like this is an issue with the virtual com port drivers. The simplest fix for Linux is libftdi.

**Comment by nedos** [comment]
You can safely close this one as the libftdi version is here: https://github.com/devio/lpcflash/pull/2
